---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: linting-pipeline-
spec:
  pipelineRef:
    name: linting-pipeline
  workspaces:
  - name: pipeline-shared-data
  volumeClaimTemplate
      spec:
        accessModes:
          - ReadWriteOnce
    resources:
          requests:
        storage: 1Gi